apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: frontend-page
  name: frontend-page
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-page
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: frontend-page
    spec:
      containers:
      - image: devopslearnerboy/website-visits
        name: website-visits
        resources: {}
status: {}
