apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: frontend-page-service
  name: frontend-page-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 31515
  selector:
    app: frontend-page
  type: NodePort
status:
  loadBalancer: {}
